include: package:pedantic/analysis_options.yaml

linter:
  rules:
    avoid_print: true
    unnecessary_this: false
    omit_local_variable_types: false
    prefer_final_fields: false
    unawaited_futures: false
    prefer_single_quotes: true
    prefer_collection_literals: false